# Generated by Django 3.2.12 on 2022-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_polaroid_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polaroid',
            old_name='track_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='polaroid',
            old_name='track_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='polaroid',
            old_name='track_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='polaroid',
            old_name='track_uri',
            new_name='uri',
        ),
        migrations.AddField(
            model_name='polaroid',
            name='is_album',
            field=models.BooleanField(default=False),
        ),
    ]
