# Generated by Django 3.2.12 on 2022-04-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220329_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polaroid',
        ),
    ]
